# Path: redaxo/src/addons/medianeo/package.yml
package: medianeo
version: '1.0.0'
author: Your Name
supportpage: https://github.com/yourusername/medianeo

requires:
    redaxo: '^5.13'
    php:
        version: '>=7.4'
    packages:
        mediapool: '^2.11'

page:
    title: 'MediaNeo'
    pjax: true
    icon: rex-icon fa-image
    subpages:
        settings:
            title: 'translate:settings'
