package: medianeo
version: '1.0.0'
author: Your Name
supportpage: github.com/yourusername/medianeo

requires:
    redaxo: '^5.13'
    php:
        version: '>=7.4'
    packages:
        media_manager: '^2.11'
        mediapool: '^2.11'

page:
    title: 'MediaNeo'
    perm: admin[]
    hidden: true
    subpages:
        ajax:
            title: 'Ajax'
            hidden: true
            pjax: false

default_config:
    preview_width: 400
    preview_height: 400
