package: medianeo
version: '2.0.0'
author: 'Dein Name'
supportpage: https://github.com/dein-username/medianeo

# Abh채ngigkeiten
requires:
    redaxo: '^5.13.0'
    php: '>=7.4'
    packages:
        filepond_uploader: '>=1.0.0'  # Abh채ngigkeit zu filepond_uploader
        yform: '>=4.0.0'              # Optional f체r YForm-Integration

# Seiten
page:
    title: 'MediaNeo'
    perm: admin
    icon: rex-icon fa-picture-o
    subpages:
        settings: { title: 'Einstellungen' }

# Standardkonfiguration
default_config:
    allowed_types: 'image/*,video/*,application/pdf'
    preview_size: 150

# Beschreibung
description: 'Ein moderner Media Picker f체r REDAXO mit FilePond Integration'
